version: "3.9"
services:
  chroma:
    image: chromadb/chroma:latest
    ports: ["8001:8000"]
    volumes: [ "./data/chroma:/data" ]
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [chroma]
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    env_file: .env
    ports: ["8501:8501"]
    depends_on: [api]
